# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WellMatching
                                 A QGIS plugin
 Wyszukiwanie tożsamych otworów geologicznych w dwóch odrębnych bazach danych.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-09
        copyright            : (C) 2020 by Dominik Szrek / PIG-PIB
        email                : dszr@pgi.gov.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WellMatching class from file WellMatching.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .well_matching import WellMatching
    return WellMatching(iface)
