# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WellMatchingDockWidget
                                 A QGIS plugin
 Wyszukiwanie tożsamych otworów geologicznych w dwóch odrębnych bazach danych.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-09
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Dominik Szrek / PIG-PIB
        email                : dszr@pgi.gov.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import pandas as pd

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from.classes import DataFrameModel

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'well_matching_dockwidget_base.ui'))

class WellMatchingDockWidget(QtWidgets.QDockWidget, FORM_CLASS):  # type: ignore

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(WellMatchingDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.adf = pd.DataFrame()
        self.bdf = pd.DataFrame()
        self.zdf = pd.DataFrame()
        self.hdf = pd.DataFrame()
        self.rdf = pd.DataFrame()

    def col_cut(self, df):
        """Zwraca dataframe bez kolumn X i Y."""
        return pd.concat(objs=[df.iloc[:,:2], df.iloc[:,4:7]], axis=1)

    def load_adf(self, df):
        """Załadowanie adf po imporcie danych A."""
        self.adf = df
        tv_adf_widths = [100, 270, 50, 50, 50]
        self.adf_mdl = DataFrameModel(df=self.col_cut(self.adf), tv=self.tv_adf, col_widths=tv_adf_widths)

    def load_bdf(self, df):
        """Załadowanie adf po imporcie danych A."""
        self.bdf = df

    def load_idf(self, dfs):
        """Załadowanie dataframe'ów indeksów po imporcie danych B."""
        for d in dfs:
            if d[0] == 'Z':
                self.zdf = d[1]
            elif d[0] == 'H':
                self.hdf = d[1]
            elif d[0] == 'ROK':
                self.rdf = d[1]

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
